import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* <head>
        <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
        <link
          href="https://unpkg.com/swiper/swiper-bundle.min.css"
          rel="stylesheet"
        />  
      </head> */}
      
      <body className={inter.className}>{children}</body>
      
    </html>
    
  );
}
